# Generated by Django 5.2.5 on 2026-04-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0009_remove_medicine_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Specialization or Department', max_length=150)),
                ('prc_license_no', models.CharField(max_length=100, unique=True, verbose_name='PRC License No.')),
                ('prc_expiry_date', models.DateField(blank=True, null=True, verbose_name='PRC License Expiry')),
                ('s2_license_no', models.CharField(blank=True, help_text='Leave blank if doctor has no S2 license', max_length=100, verbose_name='S2 License No.')),
                ('s2_expiry_date', models.DateField(blank=True, null=True, verbose_name='S2 License Expiry')),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('clinic_address', models.TextField(blank=True, verbose_name='Clinic / Hospital Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_s2_regulated',
            field=models.BooleanField(default=False, help_text='Requires a valid S2 license from the prescribing doctor', verbose_name='S2 Regulated'),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Required when dispensing S2 regulated medicines', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensings', to='PharmaSys.doctor'),
        ),
    ]
