# Generated by Django 5.2.5 on 2026-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0010_doctor_medicine_is_s2_regulated_dispensing_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPerson',
            fields=[
                ('hpatkey', models.AutoField(primary_key=True, serialize=False)),
                ('hpercode', models.CharField(blank=True, max_length=50)),
                ('hpatcode', models.CharField(blank=True, max_length=50)),
                ('patmedno', models.CharField(blank=True, max_length=50)),
                ('patlast', models.CharField(blank=True, max_length=100)),
                ('patfirst', models.CharField(blank=True, max_length=100)),
                ('patmiddle', models.CharField(blank=True, max_length=100)),
                ('patsuffix', models.CharField(blank=True, max_length=20)),
                ('patbdate', models.DateField(blank=True, null=True)),
                ('patsex', models.CharField(blank=True, max_length=10)),
                ('patcstat', models.CharField(blank=True, max_length=20)),
                ('pat_unit', models.CharField(blank=True, max_length=100)),
                ('pat_bldg', models.CharField(blank=True, max_length=100)),
                ('pat_lot', models.CharField(blank=True, max_length=100)),
                ('pat_subd', models.CharField(blank=True, max_length=150)),
                ('citcode', models.CharField(blank=True, max_length=20)),
                ('pattelno', models.CharField(blank=True, max_length=50)),
                ('pat_email', models.CharField(blank=True, max_length=150)),
                ('phicnum', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'iHOMIS Patient',
                'verbose_name_plural': 'iHOMIS Patients',
                'db_table': 'hperson',
                'ordering': ['patlast', 'patfirst'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='dispensing',
            name='ihomis_hpatkey',
            field=models.IntegerField(blank=True, db_index=True, help_text='hpatkey from iHOMIS hperson table', null=True, verbose_name='iHOMIS Patient Key'),
        ),
        migrations.AddField(
            model_name='dispensing',
            name='ihomis_hpercode',
            field=models.CharField(blank=True, default='', help_text='Cached hospital number for display', max_length=50, verbose_name='Hospital Number'),
        ),
    ]
