# Generated by Django 5.2.5 on 2026-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0011_hperson_dispensing_ihomis_hpatkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensing',
            name='ihomis_hpatkey',
            field=models.CharField(blank=True, db_index=True, default='', help_text='hpatkey from iHOMIS hperson table', max_length=50, verbose_name='iHOMIS Patient Key'),
        ),
    ]
