# Generated by Django 5.2.5 on 2026-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0012_alter_dispensing_ihomis_hpatkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Position/Designation'),
        ),
    ]
