# Generated by Django 5.2.5 on 2026-04-28 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0013_userprofile_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.BooleanField(default=False)),
                ('stock_management', models.BooleanField(default=False)),
                ('dispensing', models.BooleanField(default=False)),
                ('dispensing_card', models.BooleanField(default=False)),
                ('doctors', models.BooleanField(default=False)),
                ('suppliers', models.BooleanField(default=False)),
                ('reports', models.BooleanField(default=False)),
                ('consumption_report', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
            },
        ),
    ]
